import React from "react";
import { Alert, Box, Link, Typography } from "@mui/material";
import { Link as RouterLink } from "react-router-dom";

const DISCLAIMER_TEXT =
  "Disclaimer: The information provided on this website is for educational and informational purposes only and does not constitute financial, investment, legal, or tax advice. All content is generated by quantitative models and historical data and is not personalized to any individual user. Investing in securities involves risk, including the potential loss of principal. Past performance is not indicative of future results.";

export default function FinancialDisclaimerNotice() {
  return (
    <Alert severity="info" variant="outlined" sx={{ alignItems: "flex-start" }}>
      <Box>
        <Typography variant="body2">{DISCLAIMER_TEXT}</Typography>
        <Link
          component={RouterLink}
          to="/disclaimer"
          underline="hover"
          sx={{ display: "inline-flex", mt: 0.5, fontWeight: 600 }}
        >
          Read the full Financial Disclaimer
        </Link>
      </Box>
    </Alert>
  );
}
